# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1503433840);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1503433960);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1503433480);
user_pref("app.update.lastUpdateTime.datareporting-healthreport-lastDailyCollection", 1503434200);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1503433720);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1503433600);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1503434080);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1503508435234");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1503510188234");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1503508436507");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1503512036507");
user_pref("browser.search.countryCode", "KE");
user_pref("browser.search.region", "KE");
user_pref("browser.slowStartup.averageTime", 9066);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20160802213348");
user_pref("browser.startup.homepage_override.mstone", "45.3.0");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1503519759155");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1503433424200");
user_pref("datareporting.policy.firstRunTime", "1503433359155");
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.firstPaint", 10353);
user_pref("datareporting.sessions.current.main", 1875);
user_pref("datareporting.sessions.current.sessionRestored", 10541);
user_pref("datareporting.sessions.current.startTime", "1504728286787");
user_pref("datareporting.sessions.current.totalTime", 34);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.prunedIndex", 1);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.3.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1503433841);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.3.0");
user_pref("extensions.lastPlatformVersion", "45.3.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1470173628000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox-esr/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.3.0\",\"st\":1470173628000}}}");
user_pref("gecko.buildID", "20160802213348");
user_pref("gecko.mstone", "45.3.0");
user_pref("gfx.crash-guard.glcontext.appVersion", "45.3.0");
user_pref("gfx.crash-guard.glcontext.deviceID", "Gallium 0.4 on NVD9");
user_pref("gfx.crash-guard.glcontext.driverVersion", "3.0 Mesa 11.2.2");
user_pref("gfx.crash-guard.status.glcontext", 2);
user_pref("idle.lastDailyNotification", 1504728374);
user_pref("media.gmp-manager.buildID", "20160802213348");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1504728288);
user_pref("toolkit.telemetry.cachedClientID", "2cfca6bd-3c2e-4221-9f30-74f6878d2577");
user_pref("toolkit.telemetry.previousBuildID", "20160802213348");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
